project: coconut
save_path: /tmp/checkpoints
name: gsm8k-coconut-qwen3-a100-fresh
only_eval: true
coconut: true
cot: false
no_thoughts: false
no_cot: false
c_thought: 2
epochs_per_stage: 2
max_latent_stage: 3
pad_latent_to_max: true
save_only_improve: false
uniform_prob: 0.0
model_id: Qwen/Qwen3-4B-Instruct-2507
load_model_path: /workspace/checkpoint_1
seed: 0
resume: 1
bf16: true
train_path: data/gsm8k_train.json
val_path: data/gsm8k_validation.json
reset_optimizer: false
batch_size_training: 14
debug: false
gradient_accumulation_steps: 6
max_seq_length: 512
num_epochs: 20
lr: 1.0e-05
weight_decay: 0.01
eval_subset_size: 225

